### ISSUE TITLE
Document Safe / Unsafe Usage Patterns of temp storage

### ISSUE THREAD

**Issue by dwt** [zopefoundation/tempstorage#12] opened 2019-07-02 05:26 UTC
According to https://github.com/zopefoundation/Zope/issues/637#issuecomment-494251438 there are some systematic shortcomings of tempstorage, that I haven't seen documented in this project.

Is this the case? Is the given advice solid? If yes, there should definitely be at least a short warning section in the readme, possibly some longer form documentation that guides users about safe and unsafe ways to use this package. 

There are quite some bug-reports that point to problems with temp storage (and we are seeing problems here too) that seem to be much easier to trigger on python3, but are probably present since quite a long time. At the same time @d-maurer seems to indicate that this is common knowledge.

Quite possibly #8 is also an instance of this problem - we are seeing similar things in our internal testing, https://github.com/zopefoundation/tempstorage/issues/5, https://github.com/zopefoundation/Zope/issues/637, https://github.com/zopefoundation/Products.Sessions/issues/4 all seem to paint that there is a general problem going on.

**Comment by mgedmin** [comment] 2019-07-02 10:56
Anecdote: once I imported a folder full of page templates and scripts (a new version of our website) into /temp_folder, tested it out, then cut and pasted it into root.

About 24 hours later the new website started failing and throwing POSKeyErrors.  Turns out ZMI's Cut & Paste doesn't move the objects from one storage into another, so the Folder object pasted into the root folder was a cross-database reference into the temp storage.  Which got erased for some reason.

I wouldn't call this a bug, exactly, merely an unfortunate clash between user expectations and software working as designed.  I've learned to avoid /temp_folder.

**Comment by dataflake** [comment] 2019-07-02 11:14
@mgedmin Wow, I never ever even got the idea of storing anything at all in there. Not because I have some higher level of knowledge about tempstorage or Products.TemporaryFolder, but I never made that mental connection to think "this behaves just like a temporary folder on disk".

**Comment by dwt** [comment] 2019-07-03 06:51
@mgedmin I would have to say, that calling a function cut/copy/paste and then implementing it to merely reference some other storage without actually doing the copy is about as much a bug as the mysql utf8 encoding not actually encoding utf8 but instead only at max three bytes utf8, therefore being unable to encode smileys.

That is to say: This is utterly surprising behaviour that goes completely counter to what the user expects. It is definitely a bug - albeit one that maybe nobody wants to fix because it is complicated.

**Comment by dwt** [comment] 2019-07-03 06:53
Just a thought: If tempstorage is actually so broken - wouldn't it be sensible at some point to just drop it, move session into the normal ZODB and just be done with it?

**Comment by d-maurer** [comment] 2019-07-03 08:54
?rekcäH nitraM? wrote at 2019-7-2 23:51 -0700:
> ... CUT & PASTE does not copy ...

>That is to say: This is utterly surprising behaviour that goes completely counter to what the user expects. It is definitely a bug - albeit one that maybe nobody wants to fix because it is complicated.

At least is has not much to do with `tempstorage`.

In general, it is not unnatural that "CUT & PASTE" (unlike "COPY & PASTE")
does not copy but only moves the objects involved.
Use "COPY & PASTE", if you want a copy (potentially followed by a "DELETE"
of the original).

The "move" happens at the application level, not the ZODB level.
This can create cross database references and there *ARE* *KNOWN*
issues with cross database references (mostly, that packing can remove
objects referenced by a foreign database). Thus, you should avoid
creating cross database references (unless you know what you are
doing).

The only singularity with `tempstorage` (in this regard) is that
it is temporary: a restart deletes its complete content.
This means, use "COPY & PASTE" and never "CUT & PASTE" with
a source in a `tempstorage`.

**Comment by dwt** [comment] 2019-07-03 13:17
@d-maurer: I know this is only tangential to the bug we're discussing here, but I would really not have a problem if cut'n'paste only 'moved' objects. The problem is more that it does not. I think that is exactly the problem: It only creates a reference to the old storage location and does _not_ move the object. That is the exact reason why it the name 'cut' does not fit the mental model of users.

**Comment by dwt** [comment] 2019-07-03 13:55
I have tried experimenting a bit with the temp storage to understand it's failure states, so far I wasn't able to reproduce any of the failures that other bug reports have mentioned or that we saw.

Here's my try - can you maybe give some guidance what might be required to trigger temp storage barfing up?

```python
#!/usr/bin/env python

from contextlib import contextmanager
import time
from random import random

import ZODB, ZODB.FileStorage
from tempstorage.TemporaryStorage import TemporaryStorage
from persistent.mapping import PersistentMapping
from BTrees.OOBTree import OOBTree
import transaction

from Testing.makerequest import makerequest


storage = TemporaryStorage()
db = ZODB.DB(storage)
original_connection = connection = db.open()
root = connection.root

from OFS.Application import Application
root.Application = Application()
transaction.savepoint(optimistic=True)


def _populate(app):
    from OFS.DTMLMethod import DTMLMethod
    from Products.Sessions.BrowserIdManager import BrowserIdManager
    from Products.Sessions.SessionDataManager import SessionDataManager
    from Products.TemporaryFolder.TemporaryFolder import MountedTemporaryFolder
    from Products.Transience.Transience import TransientObjectContainer
    import transaction
    bidmgr = BrowserIdManager('browser_id_manager')
    tf = MountedTemporaryFolder('temp_folder', title="Temporary Folder")
    toc = TransientObjectContainer(
        'temp_transient_container',
        title='Temporary '
        'Transient Object Container',
        timeout_mins=20
    )
    session_data_manager = SessionDataManager(
        id='session_data_manager',
        path='/' + 'temp_folder' + '/' + 'temp_transient_container',
        title='Session Data Manager',
        requestName='SESSION'
    )
    
    app._setObject('browser_id_manager', bidmgr)
    app._setObject('session_data_manager', session_data_manager)
    app._setObject('temp_folder', tf)
    
    transaction.commit()
    
    app.temp_folder._setObject('temp_transient_container', toc)
    transaction.commit()

    # index_html necessary for publishing emulation for testAutoReqPopulate
    app._setObject('index_html', DTMLMethod('', __name__='foo'))
    transaction.commit()

_populate(root.Application)

print(connection.root)

# is a dict here good enough to check this out, or do I need to tell zodb that stuff changed#
# May need to change this to a persistent.Mapping to get the effect I want
# connection.root.session = PersistentMapping()
# connection.root.session = OOBTree()
# connection.root.session['a'] = 'b'
# print(connection.root.session['a'])
#
# import transaction
# transaction.commit()
#
# print(root.session['a'])
container = makerequest(root.Application)
session = container.session_data_manager.getSessionData()
cookies = container.REQUEST.response.cookies
cookies = {'_ZopeId': cookies['_ZopeId']['value']}
transaction.savepoint(optimistic=True)

# import sys; sys.stdout = sys.__stdout__; from pdb import set_trace; set_trace()

@contextmanager
def level(level_number):
    container = makerequest(root.Application)
    container.REQUEST.cookies = cookies
    with db.transaction() as connection:
        print(level_number, '. level')
        # import sys; sys.stdout = sys.__stdout__; from pdb import set_trace; set_trace()
        session = container.session_data_manager.getSessionData(create=False)
        print(session._p_oid)
        print(session)
        session['foo'] = level_number
        session['foo%s' % level_number] = level_number
        print(session)
        
        # print(dict(connection.root.session))
        yield session
        session['bar'] = level_number
        connection.transaction_manager.get().commit()
    print(container.session_data_manager.getSessionData()._p_changed)
    print(level_number, '. level ended')
    transaction.commit()


# with level(1):
#     with level(2):
#         with level(3):
#             with level(4):
#                 with level(5):
#                     with level(6):
#                         with level(7):
#                             with level(8):
#                                 with level(9):
#                                     pass
#
from threading import Thread

class RequestThread(Thread):
    
    def run(self):
        time.sleep(random())
        with level(1):
            with level(2):
                time.sleep(random())

t = [RequestThread() for _ in range(10000)]
list(map(lambda t: t.start(), t))
list(map(lambda t: t.join(), t))

print(session)
print(dict(session))
# print(dict(original_connection.root.session))
```

**Comment by d-maurer** [comment] 2019-07-03 16:33
?rekcäH nitraM? wrote at 2019-7-3 06:17 -0700:
>@d-maurer: I know this is only tangential to the bug we're discussing here, but I would really not have a problem if cut'n'paste only 'moved' objects. The problem is more that it does not. I think that is exactly the problem: It only creates a reference to the old storage location and does _not_ move the object.

It moves the object at the *application* level, *not* the *ZODB* level.

**Comment by dwt** [comment] 2019-07-04 10:49
Out of interest: Why does this make you think that this fact makes cut'n'paste is a good name for this feature that will give users the right mental model when to use it?

But now I'd really like to get back to the overall stability and fitness of temp storage.

**Comment by dwt** [comment] 2019-07-09 05:46
I have not been able to replicate this issue yet, but I did find out, that this patch

```patch
diff --git a/src/tempstorage/TemporaryStorage.py b/src/tempstorage/TemporaryStorage.py
index 284c55d..d61fce3 100644
--- a/src/tempstorage/TemporaryStorage.py
+++ b/src/tempstorage/TemporaryStorage.py
@@ -29,10 +29,10 @@ from ZODB.serialize import referencesf
 from ZODB.utils import z64
 
 # keep old object revisions for CONFLICT_CACHE_MAXAGE seconds
-CONFLICT_CACHE_MAXAGE = 60
+CONFLICT_CACHE_MAXAGE = 5
 
 # garbage collect conflict cache every CONFLICT_CACHE_GCEVERY seconds
-CONFLICT_CACHE_GCEVERY = 60
+CONFLICT_CACHE_GCEVERY = 5
 
 # keep history of recently gc'ed oids of length RECENTLY_GC_OIDS_LEN
 RECENTLY_GC_OIDS_LEN = 200
```

seems to make it much easier to replicate this issue in our real app. Still, I'd like to understand better what the actual issue is to ensure we have actually solved it.

**Comment by dwt** [comment] 2019-07-10 05:46
I'll be continuing the discussion about this reproducer at #8 as that seems a better bug for the kind of systematic error I'm seeing. I'd love for this bug to return to a more principled discussion of how to use tempstorage the right / wrong way.

**Comment by chrahunt** [comment] 2019-07-16 03:36
If I'm understanding correctly, this is what is failing:

1. Create a virtualenv with python2
2. Execute `pip install numpy==1.14.6 Bottleneck==1.2.1`
3. Notice that the installation operation fails

When the source distribution of Bottleneck is downloaded we attempt to build a wheel. This happens in an isolated environment independent of the other requested package installations (`numpy==1.14.6`). Because Bottleneck does not specify any version of numpy in its `setup_requires`, `setuptools` (via `easy_install`/`distutils`) attempts to download the latest numpy in order to satisfy the requirement.

Possible fixes:

1. Specify an explicit version of `numpy` in the `setup_requires` of Bottleneck's `setup.py` that is compatible with the Python versions being used
2. Install Bottleneck with `--no-build-isolation`, in which case the wheel build will take place in the same virtual environment the package is attempting to be installed into

I think pip is behaving as-expected here.

**Comment by dwt** [comment] 2019-07-22 07:37
To try and move this discussion forward: As there seems to be no developer investment in fixing / working on #8, maybe we should start thinking about deprecating this package? One first step could be to change the generator, so it doesn't always generate a tempstorage mount point for every new Zope deployment that is started. (At least until the problems outlined in #8 are fixed / under control).

What do you guys think? Is changing the generator to not create the tempstorage mountpoint a discussion that should happen in https://github.com/zopefoundation/Zope?

**Comment by zopyx** [comment] 2019-09-03 17:53
I have an issue in production with tempstorage - although not under heavy load

https://community.plone.org/t/temporarystorage-zodb-posexception-poskeyerror-0x83/9040/3

Is there any workaround?

**Comment by icemac** [comment] 2019-09-04 06:02
@zopyx Currently the only way seems to be to avoid using `tempstorage`.

**Comment by dwt** [comment] 2019-09-04 06:49
@zopyx Maybe have a look at the ideas @d-maurer provided in some of the linked bug reports - maybe you can find a way to make temp storage (again?) work?

**Comment by zopyx** [comment] 2019-09-04 09:01
Not intentionally using tempstorage. This is Plone 5.0 with a default setup.

**Comment by navytux** [comment] 2021-07-05 13:21
https://github.com/zopefoundation/tempstorage/issues/8 should be fixed now by https://github.com/zopefoundation/tempstorage/pull/16.

**Comment by dwt** [comment] 2021-07-05 15:06
When undeprecating tempstorage, the chapter in the zope book that documents the current state of storages and when to use which should be updated too:

https://zope.readthedocs.io/en/latest/zopebook/Sessions.html#alternative-server-side-session-backends-for-zope-4

**Comment by dataflake** [comment] 2021-07-05 15:52
If course. One step at a time. We don't have a fixed release yet.

**Comment by dataflake** [comment] 2021-07-05 18:59
`tempstorage` 5.2 is now released. Updates to other products that use it and external documentation is tracked elsewhere, so I will close this task:

- https://github.com/zopefoundation/Products.TemporaryFolder/issues/16
- https://github.com/zopefoundation/Products.Sessions/issues/43
- https://github.com/zopefoundation/Zope/issues/985

**Closed by dataflake** 2021-07-05 18:59 UTC
